### ISSUE TITLE
Adding first new row to new table

### ISSUE THREAD

**Issue by s1monj** [whitebrick/whitebrick#120]
- whitebrick.com/home > test_donna > formula1_demo1051 > Simon Table
- Click Add Row nothing happens
![Screen Shot 2021-12-09 at 11 36 23 PM](https://user-images.githubusercontent.com/16945182/145518100-4c3c7a4c-257c-4a97-9b86-36a93f92aa8a.png)

**Comment by VSevagen** [comment]
> We should allow for the case that the primary key column is not filled with an auto-incremented default value and instead the user manually enters a primary key value. For now I think it's better we have setting the auto increment as a second step - does it work like this?

Was able to allow user to input primary key value. We can have auto increment later if needed.

**Comment by VSevagen** [comment]
closing this issue as fixed
