### ISSUE TITLE
Adding new value to empty column not saving

### ISSUE THREAD

**Issue by s1monj** [whitebrick/whitebrick#124]
- test_donna@test.whitebrick.com > formula1_demo1051 > Circuits
- Go to last page on table
- Add a Location (eg "New York") for record 94 and press enter
- Click Circuits in the breadcrumb to reload table
- New value is not saved
- But value will save if there's an existing value in the column (eg Baku -> Baku2 for record 73)

<img width="731" alt="Screen Shot 2022-02-02 at 2 04 48 PM" src="https://user-images.githubusercontent.com/16945182/152221058-bdad957a-27d9-4ac9-be4a-b83160c631d2.png">

**Comment by s1monj** [comment]
might be related to https://github.com/whitebrick/whitebrick/issues/120

**Comment by VSevagen** [comment]
closing this issue as fixed
