### ISSUE TITLE
My Databases >  Add Database throws error

### ISSUE THREAD

**Issue by s1monj** [whitebrick/whitebrick#125]
- test_donna@test.whitebrick.com

Click "Add database" under the "My Databases" pane throws error

Using the "+" in the top right hand corner works

![Screen Shot 2022-02-07 at 1 03 43 PM](https://user-images.githubusercontent.com/16945182/152846159-92227544-9b9f-47c0-b9c1-5e911fba28d7.png)

**Comment by VSevagen** [comment]
closing this issue as fixed
