### ISSUE TITLE
Sorting single-row column throws error

### ISSUE THREAD

**Issue by s1monj** [whitebrick/whitebrick#127]
- test_donna@test.whitebrick.com > Simon Test > Test Table 1
- Click on the "_Col 1_" header to sort by the column
- Sorts correctly first click ✅ 
- Second click hangs with pin wheel and throws error in console 

![Screen Shot 2022-02-07 at 1 31 07 PM](https://user-images.githubusercontent.com/16945182/152850020-6ead201b-2495-4045-8f0d-a9bbf79ed44f.png)

**Comment by VSevagen** [comment]
closing issue as fixed
