### ISSUE TITLE
Add GraphiQL API console

### ISSUE THREAD

**Issue by s1monj** [whitebrick/whitebrick#128]
![Screen Shot 2022-02-16 at 5 19 08 PM](https://user-images.githubusercontent.com/16945182/154367485-80ba467f-8283-4d42-bc3a-64f73051cad4.png)

- Add a new button for "API"
- When clicked display the GraphiQL console
- Use the existing VARs for the URL and JWT auth
- test a few queries work as expected

Instructions/Example here: https://github.com/graphql/graphiql/tree/main/examples/graphiql-webpack

**Comment by VSevagen** [comment]
closing this as implemented
